apiVersion: v1
kind: Service
metadata:
  name: k8s-angular-srv
spec:
  type: NodePort
  selector:
    app: k8s-angular
  ports:
    - name: k8s-angular-srv
      protocol: TCP
      port: 80
      targetPort: 80
