apiVersion: v1
kind: Service
metadata:
  name: nest-node-port-srv
spec:
  type: NodePort
  selector:
    app: k8s-nest
  ports:
    - name: nest-node-port-srv
      protocol: TCP
      port: 3000
      targetPort: 3000
